### ISSUE TITLE
deploy/ release v1.0.0 crashing in heroku

### ISSUE THREAD

**Issue by clenondavis** [js-ni/weTempo-spa#1]
![image](https://user-images.githubusercontent.com/4239218/77785048-32660580-7021-11ea-8a60-ee243417d64e.png)
 
Deploying `master` branch

**Comment by clenondavis** [comment]
voy a testear quizas sea la configuracion del `procfile`

**Comment by victorstein** [comment]
Luego de revisar master me fije que no hay ningun archivo para servir el build. Estas usando algun buildpack de heroku?

**Comment by clenondavis** [comment]
heroku lo hace, cuando detecta que no hay configuraciones de ambiente, por defecto ejecuta el build y prepara para producción 

![image](https://user-images.githubusercontent.com/4239218/77786079-d13f3180-7022-11ea-903b-ed34e3133c43.png)

**Comment by clenondavis** [comment]
Es primera que me topo con este error jajajaj. Porque es primera vez que uso el proyecto `create-react-app` para prod.

Segun la documentacion de heroku el error con codigo H10 es por eso

![image](https://user-images.githubusercontent.com/4239218/77786352-490d5c00-7023-11ea-84ce-de81658b46fb.png)

**Comment by clenondavis** [comment]
revisando el log me encuentro con esto

**Comment by victorstein** [comment]
Correr react scripts para poduccion no es recomendado porque estas corriendo escuchadores de errores, el server de webpack, etc. 

para poder correr en produccion se tiene que tener un servidor pequeño de express que pueda servir los archivos que estan en la carpeta de build. Heroku no se encarga de eso de manera automatica a menos que tengas un buildpack de react.

Tambien recomiendo este link: https://medium.com/better-programming/how-to-deploy-your-react-app-to-heroku-aedc28b218ae

Para una aclaracion del deploy

**Comment by clenondavis** [comment]
https://create-react-app.dev/docs/deployment estoy revisando la configracion, y parece que hay que servir el build de forma estatica, jejejejje cuando es con create-react-app

**Comment by clenondavis** [comment]
ahhhhh, ahora recuerdo que tuve un problema similar en un hosteador. tuve que servir el contenido build y use express para eso.. Tienes mucha razon @victorstein

**Comment by jaimealv994** [comment]
me encontré esto en stackoverflow

https://stackoverflow.com/questions/44837575/react-app-crashes-on-heroku-after-using-npm-install

**Comment by jaimealv994** [comment]
Normalmente cuando despliego SPA hago build y copio esos assets para posteriormente servirlos con nginx.

**Comment by victorstein** [comment]
Has probado hacer el build despues de este merge #3 ?

**Comment by carloslenondavis** [comment]
release working good
